# Site
title:              
bio:                'Scio me nihil scire.'
description:        "Dwell in possibility"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.JPG'
background:         'assets/img/background.jpg'
locale:             en_US
url:                'https://fibomat.github.io/blog'


# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Collections
collections:
  notes:
    output: true
  comments:
    output: true


# Comments
disqus_shortname:   zhenghaoyin

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email: 		  fibomat@gmail.com	
#twitter:            username
facebook:           zehnhoff
github:             fibomat
#stackoverflow:      123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:           username
#xing:              username
#instagram:          username
#lastfm:             username
#tumblr:             username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:            username
#soundcloud:        username
weibo:             cdp1995
#flickr:            username
#codepen:           username
#keybase:           username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
